apiVersion: apps/v1
kind: Deployment
metadata:
  name: caring-saas-cloud-deployment
spec:
  selector:
    matchLabels:
      app: caring-gateway-server
  replicas: 1
  template:
    metadata:
      labels:
        app: caring-gateway-server
    spec:
      containers:
        - name: caring-gateway-server
          image: YOUR_REGISTRY/caring-gateway-server:c.2.5.1-SNAPSHOT
          ports:
            - name: http-port
              containerPort: 8760
      imagePullSecrets:
        - name: YOUR_REGISTRY_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: caring-saas-cloud
spec:
  selector:
    app: caring-gateway-server
  #    env: prod
  ports:
    - protocol: TCP
      port: 8760
      targetPort: 8760
      nodePort: 8760